### ISSUE TITLE
Any chance of auto-tracking?

### ISSUE THREAD

**Issue by JoelADerksen** [Darkened5ky/Wind-Waker-Item-and-Map-Tracker#5]
I realize this would probably be a preposterous amount of work, but is there any chance of some kind of auto-tracking being added in the future?

**Comment by Darkened5ky** [comment]
I personally will not be adding it. I love autotracking, but I know very little about Lua or how we could even interface Dolphin with EmoTracker. I'm also not inclined to learn how it would happen unless there is a console medium developed as well (since I play on console).

If someone else figures out how though, I will 100% add it in. But it's not something I foresee happening anytime soon.
